# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: Zoom.Zoom_Pckgr
PackageVersion: 5.17.10.33775
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
