# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Microsoft.Skype_Pckgr
PackageVersion: 8.112.0.210
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Skype_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://download.skype.com/s4l/download/win/Skype-8.112.0.210.exe
  InstallerSha256: BF9865599764C5D54A2F7FB58D6C3718A12659CD69FCC5BDB8500405ACDD5BF1
ManifestType: installer
ManifestVersion: 1.5.0
