# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: DuongDieuPhap.ImageGlass_Pckgr
PackageVersion: 9.0.10.201
PackageLocale: en-US
Publisher: Duong Dieu Phap
PublisherUrl: https://imageglass.org
PublisherSupportUrl: https://imageglass.org/support
Author: Duong Dieu Phap
PackageName: ImageGlass
PackageUrl: https://imageglass.org
License: GPLv3
LicenseUrl: https://github.com/d2phap/ImageGlass/blob/develop/LICENSE
Copyright: ImageGlass is copyright (c) 2010 - 2023 by Duong Dieu Phap.
CopyrightUrl: https://github.com/d2phap/ImageGlass/blob/develop/LICENSE
ShortDescription: A lightweight, versatile image viewer
Description: |-
  ImageGlass is a simple picture viewer with which you will be able to display your image collection in a very similar way to the one that Windows provides by default, but with some additional functions.
  This application will allow you to better manage your pictures thanks to the options it includes and the extension it enables to install for adding more functions and widening its possibilities.
Moniker: imageglass
Tags:
- foss
- image
- image-processing
- image-viewer
- open-source
- photo
- photo-browser
- photo-viewer
- picture
ManifestType: defaultLocale
ManifestVersion: 1.5.0

