# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Bitwarden.Bitwarden_Pckgr
PackageVersion: 2024.2.1
InstallerType: nullsoft
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- bitwarden
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/bitwarden/clients/releases/download/desktop-v2024.2.1/Bitwarden-Installer-2024.2.1.exe
  InstallerSha256: E8CB59ED7D8EA379FDD7FD02B2A85DEF3C66EAA4B5B0D88A3013FBD9C63AD4E6
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/bitwarden/clients/releases/download/desktop-v2024.2.1/Bitwarden-Installer-2024.2.1.exe
  InstallerSha256: E8CB59ED7D8EA379FDD7FD02B2A85DEF3C66EAA4B5B0D88A3013FBD9C63AD4E6
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.6.0
