# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk_Pckgr
PackageVersion: 8.0.6
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ReleaseDate: 2023-11-09
Installers:
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://download.anydesk.com/AnyDesk.exe
  InstallerSha256: EC33D8EE9C3881B8FCEA18F9F862D5926D994553AEC1B65081D925AFD3E8B028
  UpgradeBehavior: uninstallPrevious
  ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
    ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
    InstallerType: msi
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
