# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: StrawberryPerl.StrawberryPerl_Pckgr
PackageVersion: 5.38.2.2
InstallerLocale: en-US
MinimumOSVersion: 10.0.0.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
Commands:
- perl
FileExtensions:
- pl
ProductCode: '{8075BCC9-804A-1014-97A8-A0999374D9D1}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_53822_64bit/strawberry-perl-5.38.2.2-64bit.msi
  InstallerSha256: 45737AEA8B2F93C50F06EE7303EC12EAA9632763A79883AB8A8EEAE8AE96C75C
ManifestType: installer
ManifestVersion: 1.5.0
