# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: StrawberryPerl.StrawberryPerl_Pckgr
PackageVersion: 5.38.2.2
PackageLocale: en-US
Publisher: strawberryperl.com project
PublisherUrl: https://strawberryperl.com
PublisherSupportUrl: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues
Author: strawberryperl.com project
PackageName: Strawberry Perl
PackageUrl: https://strawberryperl.com
License: Perl.org
LicenseUrl: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/master/LICENSE
CopyrightUrl: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/master/LICENSE
ShortDescription: Strawberry Perl is a perl environment for MS Windows containing all you need to run and develop perl applications. It is designed to be as close as possible to perl environment on UNIX systems.
Description: |-
  Perl is a programming language suitable for writing simple scripts as well as complex applications - see https://www.perl.org

  Strawberry Perl is a perl environment for MS Windows containing all you need to run and develop perl applications. It is designed to be as close as possible to perl environment on UNIX systems.

  It includes perl binaries, compiler (gcc) + related tools, all the external libraries (crypto, math, graphics, xml ...), all the bundled database clients and all you expect from Strawberry Perl.
Moniker: strawberryperl
Tags:
- app
- development
- perl
- tools
ManifestType: defaultLocale
ManifestVersion: 1.5.0
