# Created with komac v2.0.4
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Kopia.KopiaUI_Pckgr
PackageVersion: 0.15.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2023-10-22
AppsAndFeaturesEntries:
- DisplayName: KopiaUI 0.14.1
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/kopia/kopia/releases/download/v0.15.0/KopiaUI-Setup-0.15.0.exe
  InstallerSha256: DA9F431F15AAED6A680CDFB19CF8055CF901EE2BE528E69DD1D4D58346FB461A
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/kopia/kopia/releases/download/v0.15.0/KopiaUI-Setup-0.15.0.exe
  InstallerSha256: DA9F431F15AAED6A680CDFB19CF8055CF901EE2BE528E69DD1D4D58346FB461A
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
