# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: evernote.evernote_Pckgr
PackageVersion: 10.79.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: C7D9BD7A3ECE9C77D56856024D737869470B568B824D8BFE82F7E3D4409AEF4A
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: C7D9BD7A3ECE9C77D56856024D737869470B568B824D8BFE82F7E3D4409AEF4A
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.6.0
