# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.Edge_Pckgr
PackageVersion: 123.0.2420.53
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- msedge
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
AppsAndFeaturesEntries:
- UpgradeCode: '{883C2625-37F7-357F-A0F4-DFAF391B2B9C}'
Installers:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b16f1a1a-0ecb-4566-8d28-f4460b7de5c8/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: 525ADD960BA9CC6EDFDBD16658789CC8DAB8558D601E85CDCF15A8C5220CD520
  ProductCode: '{7DE886D9-A231-3D80-92FE-A6B6202BBA9B}'
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/e795c26d-39f5-458f-a9af-73c72dd910bb/MicrosoftEdgeEnterpriseX64.msi
  InstallerSha256: 51642D33B1628BFC1947C161A43A2D94CE0D5677998D3C96FE8B3DEDE1EEC36A
  ProductCode: '{997AE1BE-0E11-3F4F-AD73-DBDD0FFEE1E6}'
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/4303e5a9-388b-4f3c-b29a-300534297599/MicrosoftEdgeEnterpriseARM64.msi
  InstallerSha256: C8E8061908D8837B8B5D24CBC74BBE60B9762A08B4EBE2FD41A671604FDA464B
  ProductCode: '{2CA5EB55-AFB0-353A-85F3-157002584BCF}'
ManifestType: installer
ManifestVersion: 1.6.0
