# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GitHub.cli_Pckgr
PackageVersion: 2.46.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- gh
ProductCode: '{3E14AE94-664D-45C5-8390-A7EC403023E3}'
AppsAndFeaturesEntries:
- UpgradeCode: '{8CFB9531-B959-4E1B-AA2E-4AF0FFCC4AF4}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cli/cli/releases/download/v2.46.0/gh_2.46.0_windows_amd64.msi
  InstallerSha256: 9A7EABEB886ED28F88FBF068EBE536899CB3BDE3A0B6862C11B8FBAD7F893755
ManifestType: installer
ManifestVersion: 1.6.0
