# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Zoom.ZoomOutlookPlugin_Pckgr
PackageVersion: 5.17.10.1010
InstallerType: msi
Scope: machine
UpgradeBehavior: install
ProductCode: '{F4E64D16-21FD-43A3-9E5F-55D8ECC5E14B}'
AppsAndFeaturesEntries:
- ProductCode: '{6FB428F1-BEAC-41DE-A15C-24EDFD4C503B}'
  UpgradeCode: '{76326AB3-064E-4680-864A-4B182236D4B9}'
Installers:
- Architecture: x86
  InstallerUrl: https://zoom.us/client/5.17.10.1010/ZoomOutlookPluginSetup.msi
  InstallerSha256: C0B486509713ADCA858F714E26AF068ECD7CB71A1B1B98B615FBD847F421C43F
ManifestType: installer
ManifestVersion: 1.6.0
