# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Discord.Discord_Pckgr
PackageVersion: 1.0.9033
InstallerLocale: en-US
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Protocols:
- discord
RequireExplicitUpgrade: true
Installers:
- Architecture: x86
  InstallerUrl: https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9033/DiscordSetup.exe
  InstallerSha256: 380317FAC753AB94B6443709A0C8F9230D829288F61038E0490938B4FB1AFF74
ManifestType: installer
ManifestVersion: 1.5.0
