# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: evernote.evernote_Pckgr
PackageVersion: 10.76.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: F50B8411415893CCC62921AC965F0EEE528EA69F479D4B0EC1899ABA5A7598AD
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: F50B8411415893CCC62921AC965F0EEE528EA69F479D4B0EC1899ABA5A7598AD
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
