# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: VMware.WorkstationPlayer_Pckgr
PackageVersion: 17.0.2
PackageLocale: en-US
Publisher: VMware, Inc.
PublisherUrl: https://www.vmware.com/products/workstation-player.html
PublisherSupportUrl: https://www.vmware.com/support/player.html
PrivacyUrl: https://www.vmware.com/help/privacy.html
Author: VMware, Inc.
PackageName: VMware Workstation Player
PackageUrl: https://www.vmware.com/products/workstation-player.html
License: Proprietary
LicenseUrl: https://www.vmware.com/help/legal.html
Copyright: Copyright © 2023 VMware, Inc. All rights reserved.
CopyrightUrl: https://www.vmware.com/help/trademarks.html
ShortDescription: VMware Workstation Player™ is a stable, mature solution for local desktop virtualization, allowing you to safely run a second operating system as a virtual machine on a single PC.
Description: VMware Workstation Player™ is a streamlined desktop virtualization application that runs another operating system on the same computer without rebooting. VMware Workstation Player provides a simple user interface, unmatched operating system support, and portability across the VMware ecosystem.
Moniker: vmware-workstation-player
Tags:
- hypervisor
- virtualmachine
- virtual-machine
ReleaseNotes: |-
  What's New

  • This release resolves CVE-2023-20869, and CVE-2023-20870. For more information on these vulnerabilities and their impact on VMware products, see VMSA-2023-0008.
ReleaseNotesUrl: https://docs.vmware.com/en/VMware-Workstation-Player/17.0.2/rn/vmware-workstation-1702-player-release-notes/index.html
ManifestType: defaultLocale
ManifestVersion: 1.4.0
