# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Google.GoogleDrive_Pckgr
PackageVersion: 86.0.2.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: --silent --skip_launch_new --gsuite_shortcuts=false
  SilentWithProgress: --silent --skip_launch_new --gsuite_shortcuts=false
ExpectedReturnCodes:
- InstallerReturnCode: 1603
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
ProductCode: '{6BBAE539-2232-434A-A4E5-9A33560C6283}'
Installers:
- Architecture: x64
  InstallerUrl: https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe
  InstallerSha256: 80504351AB04FF76DE44FA19E32302FAAD704E151E711557BE409CBDC9A7DEB2
ManifestType: installer
ManifestVersion: 1.5.0
