name: Add Automerge Label

on:
  pull_request:
    types: [opened]

jobs:
  add_remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: ubuntudroid/automerge-labeler@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'automerge' # optional
