name: Automerge PRs by PckgrTom

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'PckgrTom'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Automatic Merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: merge
          MERGE_COMMIT_MESSAGE: "auto-merge: {{actor}} merged {{head}} into {{base}}"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"
