name: Update database
on:
  push:
    branches:
      - master
    paths:
      - manifests/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: Install-Module -Name powershell-yaml -Force -Repository PSGallery -Scope CurrentUser
        shell: pwsh
      - run: .\Tools\build_database.ps1
        shell: pwsh
      - run: pip install -r Tools/requirements.txt
      - run: python Tools/write_database.py
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
